# New fields must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Common
version=1.0.0
group=com.khazoda
license=GPLv3

minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)

mod_name=KhazodaCore
mod_author=Khazoda
mod_id=khazodacore
mod_icon=khazodacore.png

description=Utility code for Khazoda's Minecraft mods
homepage_url=https://khazoda.com
sources_url=https://github.com/khazoda-mods/khazodacore
issues_url=https://github.com/khazoda-mods/khazodacore/issues

# https://fabricmc.net/develop/
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# Java & Gradle
java_version=25
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false