version=1.0.3+26.1
group=com.khazoda
license=GPLv3
#
minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)
#
mod_name=KhazodaCore
mod_author=khazoda
mod_id=khazodacore
#
description=utility code for khazoda's minecraft mods
mod_homepage=https://khazoda.com
mod_sources=https://github.com/khazoda-mods/khazodacore
mod_issues=https://github.com/khazoda-mods/khazodacore/issues
# https://fabricmc.net/develop/
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.0
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)
#
java_version=25
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false